AWSTemplateFormatVersion: "2010-09-09"
Description: >
  There is a simple API
  template for testing
  AWS CloudFormation
Resources:
  restAPIGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: serveless-api-by-CF
      EndpointConfiguration: 
        Types: 
          - REGIONAL
  restAPIGatewayGet:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      AuthorizationType: AWS_IAM
      Integration:
        IntegrationHttpMethod: GET
        Type: AWS_PROXY
        Uri: arn:aws:apigateway:region:subdomain.service|service:path|action/service_api //TODO ARRUMAR URI
  lambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: serveless-function-by-CF
      Runtime: nodejs12.x
      Handler: index.handler
      Code:
        ZipFile: |
          var aws = require('aws-sdk')
          var response = require('cfn-response')
          exports.handler = function(event, context) {
              console.log("REQUEST RECEIVED:\n" + JSON.stringify(event))
              // For Delete requests, immediately send a SUCCESS response.
              if (event.RequestType == "Delete") {
                  response.send(event, context, "SUCCESS")
                  return
              }
              var responseStatus = "FAILED"
              var responseData = {}
              var functionName = event.ResourceProperties.FunctionName
              var lambda = new aws.Lambda()
              lambda.invoke({ FunctionName: functionName }, function(err, invokeResult) {
                  if (err) {
                      responseData = {Error: "Invoke call failed"}
                      console.log(responseData.Error + ":\n", err)
                  }
                  else responseStatus = "SUCCESS"
                  response.send(event, context, responseStatus, responseData)
              })
          }
